name: Bruno API Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  bruno:
    name: Run Bruno API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: 'lts/*'
          database-url: ${{ secrets.DATABASE_URL }}
          jwt-secret: ${{ secrets.JWT_SECRET }}

      - name: Install dependencies
        run: yarn install
        working-directory: ./bruno-api

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno tests
        run: bru run --env play2do
        working-directory: ./bruno-api
